version: '3.8'
services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_USERNAME: compose-postgres
      SPRING_DATASOURCE_PASSWORD: compose-postgres
      SPRING_LIQUIDBASE_ENABLED: 'true'
      SPRING_PROFILES_ACTIVE: fixed,override
    depends_on:
      - db

  db:
    image: 'postgres:12'
    environment:
      POSTGRES_USER: compose-postgres
      POSTGRES_PASSWORD: compose-postgres
      POSTGRES_DB: MiniSocial