version: '3.8'
services:

  client:
    build:
      context: ./frontend
    ports:
    - 8081:80
    depends_on:
      - db
      - server
    networks:
      - minisocial

  server:
    build: .
    ports:
      - 8080:8080
    environment:
      MINISOCIAL_DATABASE_HOST: db
      SPRING_DATASOURCE_USERNAME: compose-postgres
      SPRING_DATASOURCE_PASSWORD: compose-postgres
    depends_on:
      - db
    networks:
      - minisocial

  db:
    image: 'postgres:12'
    environment:
      POSTGRES_USER: compose-postgres
      POSTGRES_PASSWORD: compose-postgres
      POSTGRES_DB: MiniSocial
    networks:
      - minisocial

networks:
  minisocial:
    driver: bridge