quarkus.http.port=8182

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/user_db}

quarkus.liquibase.migrate-at-start=false

kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
mp.messaging.incoming.social-events-in.connector=smallrye-kafka
mp.messaging.incoming.social-events-in.topic=social.events
mp.messaging.incoming.social-events-in.group.id=user-group
mp.messaging.incoming.social-events-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.social-events-in.auto.offset.reset=earliest

app.service-code=02

quarkus.container-image.group=nhan
quarkus.container-image.name=user-consumer
quarkus.container-image.tag=latest
quarkus.jib.base-jvm-image=eclipse-temurin:21-jre-alpine
%prod.quarkus.container-image.registry=${ECR_REGISTRY:}

quarkus.index-dependency.social-exception.group-id=com.nhan.social
quarkus.index-dependency.social-exception.artifact-id=social-exception
quarkus.index-dependency.user-service.group-id=com.nhan.social
quarkus.index-dependency.user-service.artifact-id=user-service
quarkus.index-dependency.user-service-dao.group-id=com.nhan.social
quarkus.index-dependency.user-service-dao.artifact-id=user-service-dao

quarkus.jackson.serialization-inclusion=non-null
quarkus.log.level=INFO
quarkus.log.category."com.nhan".level=DEBUG
