quarkus.http.port=8085

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/notification_db}

quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changelog/db.changelog-master.xml

mp.jwt.verify.publickey.location=${JWT_PUBLIC_KEY_LOCATION:public-key.pem}
mp.jwt.verify.issuer=${JWT_ISSUER:https://social.nhan.dev}

quarkus.redis.hosts=${REDIS_URL:redis://localhost:6379}

app.service-code=05

quarkus.container-image.group=nhan
quarkus.container-image.name=notification-api
quarkus.container-image.tag=latest
quarkus.jib.base-jvm-image=eclipse-temurin:21-jre-alpine
%prod.quarkus.container-image.registry=${ECR_REGISTRY:}

quarkus.index-dependency.social-exception.group-id=com.nhan.social
quarkus.index-dependency.social-exception.artifact-id=social-exception
quarkus.index-dependency.notification-service.group-id=com.nhan.social
quarkus.index-dependency.notification-service.artifact-id=notification-service
quarkus.index-dependency.notification-service-dao.group-id=com.nhan.social
quarkus.index-dependency.notification-service-dao.artifact-id=notification-service-dao

quarkus.jackson.serialization-inclusion=non-null
quarkus.log.level=INFO
quarkus.log.category."com.nhan".level=DEBUG
