apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-service
  namespace: social
spec:
  replicas: 1
  selector:
    matchLabels: { app: websocket-service }
  template:
    metadata:
      labels: { app: websocket-service }
    spec:
      containers:
        - name: websocket-service
          image: nhan/websocket-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://lgtm:4317
            - name: REDIS_URL
              value: redis://redis:6379
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          readinessProbe:
            httpGet: { path: /q/health/ready, port: 8080 }
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /q/health/live, port: 8080 }
            initialDelaySeconds: 40
            periodSeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  namespace: social
spec:
  selector: { app: websocket-service }
  ports:
    - port: 8080
