%dev.quarkus.http.port=8183

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/social}

quarkus.liquibase.migrate-at-start=false

quarkus.hibernate-orm.database.default-schema=post

quarkus.redis.hosts=${REDIS_URL:redis://localhost:6379}

kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
mp.messaging.incoming.interaction-events-in.connector=smallrye-kafka
mp.messaging.incoming.interaction-events-in.topic=social.events
mp.messaging.incoming.interaction-events-in.group.id=counter-group
mp.messaging.incoming.interaction-events-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.interaction-events-in.auto.offset.reset=earliest

app.service-code=03

quarkus.container-image.group=nhan
quarkus.container-image.name=post-consumer
quarkus.container-image.tag=latest
quarkus.jib.base-jvm-image=eclipse-temurin:21-jre-alpine
%prod.quarkus.container-image.registry=${ECR_REGISTRY:}

quarkus.index-dependency.social-exception.group-id=com.nhan.social
quarkus.index-dependency.social-exception.artifact-id=social-exception
quarkus.index-dependency.post-service.group-id=com.nhan.social
quarkus.index-dependency.post-service.artifact-id=post-service
quarkus.index-dependency.post-service-dao.group-id=com.nhan.social
quarkus.index-dependency.post-service-dao.artifact-id=post-service-dao

quarkus.jackson.serialization-inclusion=non-null
quarkus.log.level=INFO
quarkus.log.category."com.nhan".level=DEBUG
