name: Build jar

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Cache maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build jar
        run: |
          mvn clean package

      - name: Run project
        run: |
          docker-compose up -d --build

      - name: Waiting for process
        uses: juliangruber/sleep-action@v1
        with:
          time: 30s

      - name: CURL
        run: |
          curl http://localhost:8080

      - name: getLog
        if: ${{ always() }}
        run: |
          docker-compose logs --no-color >> log.txt

      - name: Keep log file in artifact
        if: ${{ always() }}
        run: |
          mkdir logArtifact
          cp log.txt logArtifact

      - name: Upload log artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: Log
          path: logArtifact